name: Build AML Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build
        run: |
          $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang++ \
            -std=c++17 \
            -shared \
            -fPIC \
            -O2 \
            -DNDEBUG \
            -I. \
            -s \
            -o libMyFirstMod.so \
            main.cpp \
            -llog \
            -static-libstdc++

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libMyFirstMod
          path: libMyFirstMod.so
